send:
  fields:
    title:
      required: false
      selector:
        text:
    message:
      required: true
      selector:
        text:
          multiline: true
    type:
      required: false
      default: info
      selector:
        select:
          translation_key: notification_type
          options:
            - critical
            - warning
            - info
            - reminder
    target:
      required: false
      selector:
        entity:
          multiple: true
          filter:
            integration: notification_dispatcher
            domain: sensor
