name: Hassfest

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run hassfest
        uses: home-assistant/actions/hassfest@master
