name: Validate

on:
  pull_request:
  push:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Compile integration
        run: python -m compileall custom_components
